-- MySQL Script generated by MySQL Workbench
-- Mon Jun 29 11:56:51 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `codigo_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(60) NOT NULL,
  `cpf_cliente` VARCHAR(11) NOT NULL,
  `telefone_cliente` VARCHAR(60) NOT NULL,
  `cep_cliente` VARCHAR(8) NOT NULL,
  `endereco_cliente` VARCHAR(50) NOT NULL,
  `data_nascimento_cliente` DATE NOT NULL,
  `sexo` ENUM("Masculino", "Feminino", "Outros") NULL,
  `genero_cliente` VARCHAR(30) NULL,
  `etnia_cliente` VARCHAR(30) NOT NULL,
  `nome_social_cliente` VARCHAR(60) NULL,
  `estado_civil_cliente` VARCHAR(30) NOT NULL,
  `data_cadastro_cliente` DATE NULL DEFAULT current_timestamp,
  PRIMARY KEY (`codigo_cliente`),
  UNIQUE INDEX `cpf_cliente_UNIQUE` (`cpf_cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `codigo_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(30) NOT NULL,
  `categoria` VARCHAR(30) NOT NULL,
  `descricao_produto` TEXT NOT NULL,
  `fabricante` VARCHAR(30) NOT NULL,
  `marca` VARCHAR(30) NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`codigo_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `codigo_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(60) NOT NULL,
  `cpf_funcionario` VARCHAR(11) NOT NULL,
  `rg_funcionario` VARCHAR(11) NOT NULL,
  `certidao_nascimento_filho` VARCHAR(30) NULL,
  `certificado_reservista` VARCHAR(12) NULL,
  `certidao_casamento` VARCHAR(30) NULL,
  `titulo_eleitor` VARCHAR(11) NULL,
  `telefone_funcionario` VARCHAR(15) NULL,
  `email_funcionario` VARCHAR(60) NOT NULL,
  `cep_funcionario` VARCHAR(8) NOT NULL,
  `endereco_funcionario` VARCHAR(60) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `sexo_funcionario` ENUM("Masculino", "Feminino", "Outros") NULL,
  `genero_funcionario` VARCHAR(30) NULL,
  `etnia_funcionario` VARCHAR(30) NOT NULL,
  `nome_social_funcionario` VARCHAR(60) NULL,
  `estado_civil_funcionario` VARCHAR(30) NOT NULL,
  `data_admissao` DATE NULL DEFAULT current_timestamp(),
  `data_demissao` DATE NULL,
  `escolaridade` ENUM("Fundamental", "Médio", "Graduação", "Pós-Graduação") NULL,
  `funcionariocol` VARCHAR(45) NULL,
  `pis` VARCHAR(11) NULL,
  `carteira_trabalho` VARCHAR(11) NOT NULL,
  `cargo` VARCHAR(30) NOT NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`codigo_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estoque` (
  `codigo_estoque` INT NOT NULL,
  `codigo_produto` INT NOT NULL,
  `fabricacao` DATE NOT NULL,
  `validade` DATE NOT NULL,
  `lote` VARCHAR(30) NOT NULL,
  `data_entrada` DATE NULL DEFAULT current_timestamp(),
  `quantidade_entrada` INT NOT NULL DEFAULT 1,
  `quantidade_atual` INT NOT NULL,
  `setor` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`codigo_estoque`),
  INDEX `fk_estoque_produto_idx` (`codigo_produto` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_produto`
    FOREIGN KEY (`codigo_produto`)
    REFERENCES `mydb`.`produto` (`codigo_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `codigo_venda` INT NOT NULL AUTO_INCREMENT,
  `codigo_cliente` INT NOT NULL,
  `codigo_funcionario` INT NOT NULL,
  `data_hora` DATETIME NOT NULL DEFAULT current_timestamp(),
  `total` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`codigo_venda`),
  INDEX `fk_venda_funcionario1_idx` (`codigo_funcionario` ASC) VISIBLE,
  INDEX `fk_venda_cliente1_idx` (`codigo_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`codigo_funcionario`)
    REFERENCES `mydb`.`funcionario` (`codigo_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`codigo_cliente`)
    REFERENCES `mydb`.`cliente` (`codigo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itens da venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`itens da venda` (
  `codigo_itens_venda` INT NOT NULL AUTO_INCREMENT,
  `desconto` DECIMAL(4,2) NULL,
  `quantidade` INT NOT NULL,
  `subtotal` DECIMAL(7,2) NULL,
  `codigo_venda` INT NOT NULL,
  `codigo_produto` INT NOT NULL,
  PRIMARY KEY (`codigo_itens_venda`),
  INDEX `fk_itens da venda_venda1_idx` (`codigo_venda` ASC) VISIBLE,
  INDEX `fk_itens da venda_produto1_idx` (`codigo_produto` ASC) VISIBLE,
  CONSTRAINT `fk_itens da venda_venda1`
    FOREIGN KEY (`codigo_venda`)
    REFERENCES `mydb`.`venda` (`codigo_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens da venda_produto1`
    FOREIGN KEY (`codigo_produto`)
    REFERENCES `mydb`.`produto` (`codigo_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pagamento` (
  `codigo_pagamento` INT NULL AUTO_INCREMENT,
  `forma_pagamento` ENUM("Pix", "Débito", "Crédito", "Dinheiro", "Voucher") NOT NULL,
  `informacoes_cartao` VARCHAR(255) NULL,
  `total_pagamento` DECIMAL(7,2) NOT NULL,
  `valor_recebido` DECIMAL(5,2) NOT NULL,
  `troco` DECIMAL(4,2) NULL,
  `numero_parcelas` INT NOT NULL,
  `valor_parcela` DECIMAL(7,2) NULL,
  `status_pagamento` ENUM("Pix", "Débito", "Crédito", "Dinheiro", "Voucher") NOT NULL DEFAULT '\"Pendente\"',
  `codigo_venda` INT NOT NULL,
  PRIMARY KEY (`codigo_pagamento`),
  INDEX `fk_pagamento_venda1_idx` (`codigo_venda` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_venda1`
    FOREIGN KEY (`codigo_venda`)
    REFERENCES `mydb`.`venda` (`codigo_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
